### ISSUE TITLE
recaptchav2  Cannot be used

### ISSUE THREAD

**Issue by chenpython** [0xNev/Captcha-Harvester#1]
recaptchav2   Cannot be used
Test URL:https://www.walmart.com/blocked   （Try a different method）

**Comment by n3-v** [comment]
Are you having trouble getting the captcha tokens on https://www.walmart.com/blocked or are the tokens not appearing valid?

**Comment by chenpython** [comment]
The webdriver opens the website and does not move, does not perform the verification code operation, and then keeps jamming the application.

**Comment by n3-v** [comment]
Could you send me your code and output if any?

**Comment by chenpython** [comment]
import pyharvester
harvester_1 = pyharvester.new(solver_type="recaptchav2", url="https://www.walmart.com/blocked", site_key="6Lck6mQbAAAAAExAa3USDzPH7qr20yawxDVuf_W1", action="examples/v3scores")
captcha_token = harvester_1.solve(timeout=100)
print(captcha_token)


Chrome display captcha page does not move, then has been stuck where, python program no output

**Comment by n3-v** [comment]
I tried that code exactly in a new venv and it seemed to work fine, are you able to harvest captchas on other sites?
